AUTHORS, CONTRIBUTORS, Dockerfile
With more recent Ubuntu/Debian, I get this build error when running `ninja -C out/Debug`:
```
../../packager/media/formats/webm/webm_cluster_parser_unittest.cc:603:21: error: default initialization of an object of const type 'const BufferQueue' (aka 'const deque<scoped_refptr<shaka::media::MediaSample> >') without a user-provided default constructor
const BufferQueue no_text_buffers;
^
{}
1 error generated.
[1238/1302] CXX obj/hls/base/hls_unittest.simple_hls_notifier_unittest.o
ninja: build stopped: subcommand failed.
```
Since CI (Travis) is running Ubuntu 12.04, it seems like a safe bet for the development/test Dockerfile.
I'm working on the corporate CLA now...
=> Specify Ubuntu 14.04 in Dockerfile to ensure successful build

packager/media/base/fixed_key_source.h
The existing link broke apparently due to a restructuring of the W3C Drafts site.
In the meantime, this part of the Draft became a Note, to which I have made a new short link.
=> Fix broken link to W3C "cenc" Inititialization Data Format documentation

CONTRIBUTORS, appveyor.yml
Change output directory name to %CONFIGURATION%_x64 on x64 platform.
Add a new contributor.
Issue #168
=> Fix appveyor.xml for x64 Windows CI.

packager/mpd/base/mpd_builder.cc
This is a fix for issue #216 where the Representation::SlideWindow() logic was
still active even though a static MPD was being asked to be generated (using
the option -generate_static_mpd). This could cause static streams longer than
1800 seconds to start playing at (end-position-for-stream - 1800 seconds).
This change is in compliance with the current usage documentation for the
shaka-packager, which suggests that -time_shift_buffer_depth only is relevant
for dynamic media presentations.
=> Don't do timeshift SlideWindow() logic for static MPD

packager/app/packager_main.cc, packager/app/stream_descriptor.cc, packager/app/stream_descriptor.h, packager/app/test/packager_test.py, packager/app/test/testdata/bear-640x360-a-clear-v-cenc-golden.mpd
This option makes it possible to control encryption for specific streams, i.e. for audio and video separately.
In my set-up, I want to have the ability to control which tracks gets to be encrypted or not (in my case, I wanted the sound to be in clear). I though that others perhaps wanted this capability as well, hence the pull request. 
It's possible though that the maintainers think otherwise :) Let's have a try.
=> Add support for skip_encryption stream descriptor

docs/source/build_instructions.md
Fixed a typo on the instruction for launching the install-build-deps script, needed to install all the cross-compiler and library dependencies on Ubuntu platforms.
=> Fix typo for ARM cross-compile instructions

packager/media/base/aes_pattern_cryptor.cc
The condition was the same in meaning,
but a bit confusing in syntax.
=> Clear up condition in AesPatternCryptor

AUTHORS, CONTRIBUTORS, packager/media/base/key_source.h, packager/media/base/playready_key_source.cc, packager/media/base/playready_key_source.h, packager/media/base/raw_key_source.cc, packager/media/base/raw_key_source.h, packager/media/base/widevine_key_source.cc, packager/media/base/widevine_key_source.h, packager/media/base/widevine_key_source_unittest.cc, packager/media/crypto/encryption_handler.cc, packager/media/crypto/encryption_handler_unittest.cc
When using key rotation with Widevine DRM, a key server has to know
the duration of crypto period to relate generated keys to the media
playback time. This helps the server to provide relevant keys to
a client during license request.
Closes #544.
=> Add crypto_period_seconds to Widevine key request

packager/file/udp_file.cc
This PR will cleanup condition for `bind` (`bind` returns `-1` on error)
=> Cleanup condition on `bind` error

docs/source/options/general_encryption_options.rst
Added a better description to `clear_lead` docs with the same content as defined in the change log (https://github.com/google/shaka-packager/commit/9e9833ea63cf75c2bcd3d1ee8202c92450e5b461). I'm learning about the DRM and it took me hours to figure out why my segments were not being encrypted (similar to https://github.com/google/shaka-player/issues/1883).
=> Update general_encryption_options with a better clear_lead description

docs/source/options/dash_options.rst, docs/source/tutorials/ads.rst, docs/source/tutorials/dash.rst, packager/app/mpd_flags.cc, packager/app/mpd_flags.h, packager/app/packager_main.cc, packager/app/retired_flags.cc, packager/app/test/packager_test.py
=> Replace `generate_static_mpd` to `generate_static_live_mpd`

docs/source/options/hls_options.rst, packager/app/hls_flags.cc, packager/app/hls_flags.h, packager/app/packager_main.cc, packager/hls/base/media_playlist.cc, packager/hls/base/media_playlist.h, packager/hls/public/hls_params.h
See #691 for details on the use cases behind this.
Regarding the code changes:
* A new command line argument is added.
* `media_sequence_number` variable was changed to unsigned, as otherwise "big" media sequence numbers would end up negative, and there's no reason for this var not being unsigned.
* There's also a new logic case for medialists that checks when this parameter is present and activates the discontinuity tag mechanics.
=> New command line argument: hls_media_sequence_number

packager/version/generate_version_string.py
As outlined [here](https://github.com/google/shaka-packager/issues/724), the `gclient sync` command was throwing a `python` `subprocess` related error. The call to the subprocess library required an additional `shell=True` argument to be passed in the `generate_version_string.py` file.
=> Fix the error thrown by runhooks command on Windows [Issue 724]

packager/tools/generate_license_notice.py
Added parentheses to `print` methods to fix the build error.
The following error occured before this change.
```console
$ python --version
Python 3.7.7
$ gclient config https://www.github.com/google/shaka-packager.git --name=src --unmanaged
...
$ gclient sync
...
$ cd src
$ ninja -C out/Release
ninja: Entering directory `out/Release'
[1/1670] ACTION Generating embeddable license
FAILED: gen/packager/tools/license_notice.cc gen/packager/tools/license_notice.h
cd ../../packager/tools; python generate_license_notice.py /home/user/shaka-packager/src/out/Release/gen/packager/tools
File "generate_license_notice.py", line 119
print 'Num License Files: {}\n'.format(len(license_files))
^
SyntaxError: invalid syntax
[3/1670] CXX obj/third_party/protobuf/src/g...f/util/protobuf_full_do_not_use.time_u …
```
=> Fixed build error in Python 3

README.md, packager/media/codecs/es_descriptor.cc, packager/media/codecs/es_descriptor.h, packager/media/formats/mp4/mp4_muxer.cc
- Makes possible to pack mpeg1 audio streams into .mp4 files
=> Mpeg1 Audio: Support for iso-bmff output, ref #779

CONTRIBUTORS, docs/source/options/raw_key_encryption_options.rst, docs/source/tutorials/raw_key.rst, packager/app/packager_main.cc, packager/media/base/raw_key_source.cc, packager/media/public/crypto_params.h
Allow an optional initialization vector to be specified as `iv` in the "key_info_string" for raw key encryption. This is for use in conjunction with FairPlay where the IV will be delivered from the KSM, not the randomized one otherwise supplied in the ISO BMFF `tenc` box. The --iv option is mutually exclusive with this key parameter.
=> Allow IV to be specified in the "key_info_string"

packager/media/formats/mp4/box_definitions.cc
#812  Packaging fails if input content contains SampleGroupDescriptionBox with 0 entries.
Made required changes to the file -  packager/media/formats/mp4/box_definitions.cc to fix the issue.
=> Made changes in media/mp4/box_definitions.cc to fix issue812

packager/tools/pssh/pssh-box.py
I'm not a fluent python developer but I put some effort to fix python 3 errors and make this tool still usable under python 2.
I tried all sample options from https://github.com/google/shaka-packager/blob/master/packager/tools/pssh/README.md and they work with python 2.7 and 3.8.6
e.g.
```
$ python2 out/Debug/pssh-box.py --widevine-system-id --content-id 1231897231 --hex
000000277073736800000000EDEF8BA979D64ACEA3C827DCD51D21ED0000000722051231897231
$ python7 out/Debug/pssh-box.py --widevine-system-id --content-id 1231897231 --hex
000000277073736800000000EDEF8BA979D64ACEA3C827DCD51D21ED0000000722051231897231
```
Fixes #833
=> pssh-box python 3 errors fix

packager/media/formats/webvtt/webvtt_parser.cc
Fixes: https://github.com/google/shaka-packager/issues/882
```
$ packager 'in=SampleVideo_1280x720_30mb.mp4,stream=video,init_segment=/tmp/SampleVideo_1280x720_30mb/init.m4v,segment_template=/tmp/SampleVideo_1280x720_30mb/seg_$Number$.m4s' 
'in=SampleVideo_1280x720_30mb.mp4,stream=audio,init_segment=/tmp/SampleVideo_1280x720_30mb-audio/init.m4v,segment_template=/tmp/SampleVideo_1280x720_30mb-audio/seg_$Number$.m4s,lang=en' 
'in=SampleVideo_1280x720-web.vtt,stream=text,init_segment=/tmp/SampleVideo_1280x720_30mb-vtt/vtt_init.m4v,language=en,segment_template=/tmp/SampleVideo_1280x720_30mb-vtt/seg_$Number$.m4s' 
--clear_lead 0 --segment_duration 6 --fragment_duration 6 --generate_static_live_mpd 
--mpd_output /tmp/SampleVideo_1280x720_30mb/stream.mpd
```
=> WEBVTT - support center and middle text alignment

packager/packager.cc
Fixes https://github.com/google/shaka-packager/issues/883
Example: 
Input:
./packager 'in=/YR_12025_jb_2CH_401160_375.mp4,stream=video,init_segment=/YR_12025_jb_2CH_401160_375/init.m4v,segment_template=/420776_cenc_dash/YR_12025_jb_2CH_401160_375/seg_$Number$.m4s,drm_label=sd' 'in=/YR_12025_jb_2CH_401160_2100.mp4,stream=video,init_segment=/YR_12025_jb_2CH_401160_2100/init.m4v,segment_template=/YR_12025_jb_2CH_401160_2100/seg_$Number$.m4s,drm_label=hd' 'in=/YR_12025_jb_2CH_en-US_401160_3_aac_128.mp4,stream=audio,init_segment=/YR_12025_jb_2CH_en-US_401160_3_aac_128/init.m4v,segment_template=/YR_12025_jb_2CH_en-US_401160_3_aac_128/seg_$Number$.m4s,lang=en,drm_label=audio' 'in=/en/en.vtt,stream=text,init_segment=/en/vtt_init.m4v,language=en,segment_template=/en/seg_$Number$.m4s' --clear_lead …
=> [DASH] - encryption validation only for non-text streams

CONTRIBUTORS, packager/tools/pssh/pssh-box.py
The implementation is wrong for some value, which leads to wrong pssh box generation from pssh data.
Example: value = 132, below is the result in python3 shell. (python 3.6.9)
```
>>> value=132
>>> (chr(value >> 24) + chr((value >> 16) & 0xff) + chr((value >> 8) & 0xff) + chr(value & 0xff)).encode()
b'\x00\x00\x00\xc2\x84'
>>> import struct
>>> struct.pack('>i', value)
b'\x00\x00\x00\x84'
```
The previous implementation outputs 5 bytes which is wrong.
=> Fix wrong _create_bin_int implementation in pssh-box.py

docs/source/build_instructions.md
Feel free to change the text as much as you like. I'd just like to see IDE support mentioned.
Alternatively the CMakeLists.txt generation could be mentioned.
=> Ide instructions doc #772

DEPS, docs/source/build_instructions.md, packager/media/chunking/cue_alignment_handler.h
Summary of changes:
- In order to use MSVS 2019, gyp must be upgraded.  The old version didn't recognize MSVS 2019, but the newer version does.
- Skip clang downloads on Windows.  The older clang download tools don't recognize the MSVS 2019 environment.  We aren't using clang for a Windows build anyway, so just skip this hook when running gclient sync.
- Because a StreamState object contains a unique_ptr, it is not copyable.  A vector of StreamStates, therefore, causes a compile error on resize or push_back, both of which invoke the copy constructor.
I don't know why MSVS complains, but clang does not. To fix this, I'm changing vector<StreamState> into deque<StreamState>.
- The build instructions have been updated with necessary environment variables for newer MSVS versions.
At this point …
=> Fix MSVS 2019 builds

packager/common.gypi, packager/file/file.gyp, packager/file/file.h, packager/packager.gyp
To make shared_library builds work on Windows with MSVS 2019, this
commit:
- Silences a useless warning about a private member in dll-exported
Status class.
- Exports the File class used by packager.exe
- Removes the explicit File dependency in packager.exe in favor of
libpackager, now that File is exported
- Add missing defines in packager.exe and packager_test.exe that
instruct the linker to import Status and File from the library
Closes #318 (shared_library builds on Windows)
Issue #336 (progress toward GitHub Actions workflow to replace Travis
and Appveyor, where we need to build and test shared_library on all
platforms)
b/190743862 (internal; tracking replacement of Travis)
=> Fix Windows shared_library builds

packager/common.gypi
Shared library builds worked, but failed tests because they were made
with the wrong CRT linker settings.  Strings allocated within the
library could not be freed outside the library because the dynamic CRT
was not used.
This sets necessary gyp variables to link with a dynamic CRT on
Windows, thereby fixing tests running in shared library mode that
otherwise hung in a GitHub Actions environment.
Related to #318 (shared_library builds on Windows)
Issue #336 (progress toward GitHub Actions workflow to replace Travis
and Appveyor, where we need to build and test shared_library on all
platforms)
b/190743862 (internal; tracking replacement of Travis)
=> Fix shared library test runs on Windows

packager/common.gypi
In e2efb5d4, I fixed shared_library builds on Windows, but I
introduced another issue in which the libpackager_type variable was
not correctly defined by default.  This meant that the build only
worked with this variable explicitly-defined in GYP_DEFINES when
gclient sync was run.
This fixes the default definition so that libpackager_type does not
need to be defined explicity.
Related to #318 (shared_library builds on Windows)
Issue #336 (progress toward GitHub Actions workflow to replace Travis
and Appveyor, where we need to build and test shared_library on all
platforms)
b/190743862 (internal; tracking replacement of Travis)
Change-Id: If353e1d3c312ab0c568d4d4d2b789e922d7216e1
=> Fix libpackager_type variable undefined by default

.github/workflows/README.md, .github/workflows/github_release.yaml, .github/workflows/update_docs.yaml
There is not a good reason to use a long-lived token attached to
@shaka-bot.  Instead, use a short-lived, automatic token generated by
GitHub Actions for the workflow run.
=> ci: Use GITHUB_TOKEN instead of SHAKA_BOT_TOKEN

.github/workflows/custom-actions/build-packager/action.yaml, packager/common.gypi
We never produced static release executables on Linux before, but the dynamic libraries they depended on were universal enough that nobody noticed.  Now that we have released v2.5 and switched to GitHub Actions for CI builds, the Linux executables depend on libatomic, which is causing issues for some users.
Although we can't create fully-static executables on macOS or Windows, we can at least do so on Linux.
This adds a GYP variable `static_link_binaries` which can be set to request full-static binaries on Linux.  This also exposes the Chromium build variable `disable_fatal_linker_warnings`, which is necessary when static linking on Linux due to static-link-related warnings generated by libcurl for its use of `getaddrinfo`.  Finally, this enforces the definition of `__UCLIBC__` with …
=> ci: Produce static release executables on Linux

packager/media/event/combined_muxer_listener.cc, packager/media/event/combined_muxer_listener.h, packager/media/event/mpd_notify_muxer_listener.cc, packager/media/event/mpd_notify_muxer_listener.h, packager/media/event/muxer_listener.h, packager/media/formats/mp4/low_latency_segment_segmenter.cc, packager/media/formats/mp4/low_latency_segment_segmenter.h, packager/mpd/base/mock_mpd_notifier.h, packager/mpd/base/mpd_notifier.h, packager/mpd/base/representation.cc, packager/mpd/base/representation.h, packager/mpd/base/representation_unittest.cc, packager/mpd/base/simple_mpd_notifier.cc, packager/mpd/base/simple_mpd_notifier.h
- With LL-DASH mode enabled, the gap size warning was hit and printed to the console every time a new segment was registered to the manifest.
- This occurred because the first chunk's size and duration were being stored for each segment, rather than the full segment size and duration. Note, only the first chunk's metrics are known at first because in low latency mode, the segment is registered to the manifest before it is finished being processed and written.
- Because of this, the gap size check was comparing the end time of the first chunk in the previous segment to the beginning time of the current segment, causing the check to fail every time.
- Update a low latency segment's duration and size once the segment file has been fully written.
- The full segment size and duration will be …
=> Fix for gap size warning in Low Latency mode

.github/workflows/build_and_test.yaml, .github/workflows/custom-actions/build-packager/action.yaml, .github/workflows/github_release.yaml, Dockerfile, docs/source/build_instructions.md, packager/testing/dockers/Alpine_Dockerfile, packager/testing/dockers/ArchLinux_Dockerfile, packager/testing/dockers/CentOS_Dockerfile, packager/testing/dockers/Debian_Dockerfile, packager/testing/dockers/Fedora_Dockerfile, packager/testing/dockers/OpenSUSE_Dockerfile, packager/testing/dockers/Ubuntu_Dockerfile
Using the latest depot_tools no longer works.  depot_tools also wants
to auto-update itself, which must now be disabled.
We also need to disable the copy of python (vpython) included in
depot_tools, since for some distros, it has dependencies on system
libraries that no longer exist.
Finally, we need to force some distros to use python 2, because our
build system is ancient and needs to be ripped out and replaced some
day soon.
This fixes build issues in our CI, our Dockerfiles, and in general on
certain platforms or distros.
Closes #1023
=> fix: Roll back depot_tools, bypass vpython

packager/media/formats/webvtt/webvtt_parser.cc, packager/media/formats/webvtt/webvtt_parser_unittest.cc
Fixes: https://github.com/shaka-project/shaka-packager/issues/1018
While Parsing cue body check for the block size. 
If it's the last block do not error if it doesn't have a newline.
=> fix: webvtt single cue do not fail on EOS

docs/source/options/dash_stream_descriptors.rst, packager/app/packager_main.cc, packager/app/test/packager_test.py, packager/app/test/testdata/audio-video-with-accessibilities-and-roles/output.mpd, packager/mpd/base/adaptation_set.cc, packager/mpd/base/adaptation_set.h, packager/mpd/base/period.cc
Fixes support for description role for audio DVS tracks. 
as per spec:
=> fix: dash_roles add role=description for DVS audio per DASH-IF-IOP-v4.3

packager/media/formats/mp2t/program_map_table_writer.cc, packager/media/formats/mp4/mp4_media_parser.cc
This PR fixes some build errors on Fedora Linux with `g++ (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1)`.
=> fix: Fix build errors related to std::numeric_limits

README.md
Releases will no longer be announced on the mailing list. Instead,
users can subscribe directly through GitHub.
=> docs: Deprecate the mailing list for releases

CONTRIBUTORS, packager/media/codecs/aac_audio_specific_config.cc, packager/media/codecs/aac_audio_specific_config.h, packager/media/codecs/aac_audio_specific_config_unittest.cc
Note:
* An xHE-AAC capable encoder will auto adjust the user-specified SAP/RAP
value to the allowed grid where SAP/RAPs can occur.
e.g.: `-rapInterval 5000` (5s) may result in actual SAPs/RAPs every 4.984s.
* To ensure SAP/RAP starts a new segment, Shaka needs to executed with a
"--segment_duration" is less than or equal to that adjusted value.
* If every SAP/RAP should trigger a new segment, just set the segment
length to a very low value e.g.: `--segment_duration 0.1`
=> feat: Add xHE-AAC support

.github/workflows/build-docs.yaml, docs/source/conf.py
The docs build in GitHub Actions broke with the release of jinja 3.1, which introduced a breaking change that broke the cloud_sptheme sphinx extension in use by our docs.  That extension is not maintained any more, so there will be no upstream fix.  See also https://foss.heptapod.net/doc-utils/cloud_sptheme/-/issues/47
That extension adds support for table styling (see https://cloud-sptheme.readthedocs.io/en/latest/lib/cloud_sptheme.ext.table_styling.html), but we only appear to have one table in the docs currently (docs/source/options/segment_template_formatting.rst) and it does not use the options added by the cloud_sptheme extension.
Therefore the best fix for GitHub Actions and any other system running jinja 3.1 is to remove that extension from our config.
=> ci: Fix docs build in GitHub Actions

.github/workflows/build.yaml
Build in parallel with however many cores are available on the system. This might not affect build times in every environment (for example, if GitHub Actions VMs are single core).
From the initial test run of this PR, we're seeing roughly 1x build speed on Linux, 3x on macOS, and 1.5x on Windows, compared to the same build step on a contemporaneous PR.
=> ci: Parallel build

.github/workflows/pr.yaml
If another instance of the PR workflow is started for the same PR,
cancel the old one.  If a PR is updated and a new test run is started,
the old test run will be cancelled automatically to conserve
resources.
=> test: Cancel workflow when a PR is updated

.github/workflows/build.yaml
It is not necessary to change directory before invoking ctest.
Issue #1047 (CMake porting)
=> ci: Improve test command in build workflow

packager/file/callback_file.cc, packager/file/file.h, packager/file/http_file.cc, packager/file/io_cache.h, packager/file/thread_pool.h, packager/file/udp_options.cc, packager/macros.h, packager/status/status.cc
=> refactor: Rename common.h to macros.h, now that it only contains macros

packager/status/CMakeLists.txt, packager/status/status_macros.h, packager/status/status_test_util.h, packager/status/status_test_util_unittest.cc
For some reason, the status util unittest was in media/base/ instead of status/
The broken headers in the status library were not obviously broken until media/base/ porting started, and they were used for the first time.
Issue #1047 (CMake porting)
=> fix: Fix status library headers and move test

packager/media/codecs/h264_parser.cc, packager/media/codecs/h264_parser.h, packager/media/codecs/h265_parser.cc, packager/media/codecs/h265_parser.h, packager/media/formats/mp2t/es_parser_h264.cc, packager/media/formats/mp2t/es_parser_h264.h, packager/media/formats/mp2t/es_parser_h265.cc, packager/media/formats/mp2t/es_parser_h265.h, packager/media/formats/mp2t/es_parser_h26x.cc, packager/media/formats/mp2t/es_parser_h26x.h, packager/media/formats/mp2t/es_parser_h26x_unittest.cc, packager/media/formats/mp2t/mp2t_media_parser.cc, packager/media/formats/mp2t/ts_section_pes.cc
=> fix: Parse one frame mpeg-ts video

packager/testing/test_dockers.sh
This seems to bring current docker build times in the cmake branch from 4-6 minutes down to 3-4 minutes.
=> ci: Use multiple cores in docker tests

packager/file/file_test_util.h, packager/file/udp_options.cc, packager/macros.h, packager/media/base/aes_cryptor_unittest.cc
This does not depend on absl, which frees macros.h from any library deps that would make the CMake dependency tree more complicated.  This also fixes build errors in some environments.
=> feat: Replace arraysize with std::size

.github/workflows/build.yaml, packager/testing/test_dockers.sh
This appears to fix some issues with crashing compilers on arm64 and docker builds.  This may be caused by resource constraints in those environments.
=> ci: Disable parallel builds

packager/tools/pssh/pssh-box.py
A single-line change on #L170 to `wv.protection_scheme = struct.unpack('>L', bytes(protection_scheme, encoding='utf-8'))[0]`, needed to work around this issue on Ubuntu 22.04LTS+ running Python 3.10+:
```sh
TypeError: a bytes-like object is required, not 'str'
```
On line 170.
=> fix: Fix type error in pssh-box.py with Python 3.10+

packager/third_party/protobuf/python/google/protobuf/internal/containers.py
This issue is observed on Python 3.10+ and above.
This workaround addresses a major backwards compatibility break with a major Python release version where collections.abc isn't available.
Fixes #1192
=> fix: Fix issues with `collections.abc` in Python 3.10+

packager/testing/dockers/OpenSUSE_Dockerfile
Using a rolling release of OpenSUSE was unstable.  But there is another way around the old compiler in OpenSUSE 15.  This upgrades the compiler while staying on a stable release of the OS.
=> test: Fix OpenSUSE docker build

AUTHORS, CONTRIBUTORS, packager/media/formats/ttml/ttml_generator.cc, packager/media/formats/ttml/ttml_generator_unittest.cc
Fix bug where milliseconds were formatted with two digits instead of three, resulting in incorrect timestamps in TTML cues.
Fixes https://github.com/shaka-project/shaka-packager/issues/1180
=> fix: TTML generator timestamp millisecond formatting

docs/source/build_instructions.md
The default branch is `main`, not `master`. Indicate this on the documentation as its' not obvious.
Fixes #1060
=> docs: Update build_instructions.md to point to the `main` branch.

packager/mpd/base/representation_unittest.cc, packager/mpd/base/xml/xml_node.cc, packager/mpd/base/xml/xml_node_unittest.cc
Low Latency DASH manifests generated by Packager were missing the attribute `availabilityTimeComplete`. As per the [DASH specs](https://dashif.org/docs/CR-Low-Latency-Live-r8.pdf):
**_the AdaptationSet@availabilityTimeCompleteshould be present and be set to 'FALSE'_**
The missing attribute caused ULL streams from Shaka Packager to no longer be compatible with DASH.js. Previous versions of DASH.js allowed users to specify ULL mode when initializing the player. However, the most recent releases of DASH.js automatically detect ULL by scanning the manifest for ULL specific attributes. Although there are many attributes only associated with ULL, [DASH.js only greps for `availabilityTimeComplete` in its detection logic](https://github.com/Dash-Industry-Forum/dash.js/blob/development/src/streamin …
=> fix: Low Latency DASH: include the "availabilityTimeComplete=false" attribute

packager/file/http_file.cc
Closing the upstream on flush will effectively terminate the ongoing curl connection. This means that we would need re-establish the connection in order to resume writing, this is not what we want. In the spirit of the documentation of File::Flush
```c++
/// Flush the file so that recently written data will survive an 
/// application crash (but not necessarily an OS crash). For 
/// instance, in LocalFile the data is flushed into the OS but not 
/// necessarily to disk.
```
We will instead wait for the curl thread to finish consuming what ever might be in the upload cache, but leave the connection open for subsequent writes.
Fixes #1196
=> fix: Don't close upstream on HttpFile::Flush

packager/tools/pssh/pssh-box.py
=> fix: Indexing `bytes` produces `int` on python3 for `pssh-box.py`

packager/media/demuxer/demuxer.cc
Fix a bug that if the webvtt file is very short, e.g. only contains one block
WEBVTT
00:00:00.500 --> 00:00:02.000
The Web is always changing
shaka packager will report error: "Packaging Error: 6 (END_OF_STREAM)".
Fixes #1217
=> fix: Fix failure on very short WebVTT files

packager/mpd/base/mpd_builder.cc
While I have not yet found why the periods are empty, this will prevent shaka from seg faulting
Fixes #1172
=> fix: Prevent crash in GetEarliestTimestamp() if periods are empty

packager/file/http_file.cc, packager/file/http_file.h, packager/file/http_file_unittest.cc, packager/media/base/http_key_fetcher.cc, packager/media/base/http_key_fetcher.h, packager/media/base/http_key_fetcher_unittest.cc
This reverts commit 2e349845c60958820b043a82987da479f3d2956d from PR #1203.
We are moving away from httpbin.org for testing, and this revert will make subsequent changes to the tests easier to read.
=> test: Revert "Retry HTTP file tests on temporary httpbin failure"

packager/file/callback_file.cc, packager/file/callback_file.h, packager/file/file.h, packager/file/http_file.cc, packager/file/http_file.h, packager/file/http_file_unittest.cc, packager/file/local_file.cc, packager/file/local_file.h, packager/file/memory_file.cc, packager/file/memory_file.h, packager/file/threaded_io_file.cc, packager/file/threaded_io_file.h, packager/file/udp_file.cc, packager/file/udp_file.h, packager/media/base/CMakeLists.txt, packager/media/base/http_key_fetcher.cc, packager/media/base/http_key_fetcher_unittest.cc, packager/third_party/mongoose/CMakeLists.txt
All HTTP-based tests now use an embedded test server instead of
httpbin.org, which makes them much faster and more reliable.
These more reliable tests also exposed some issues that began recently
with PR #1201.  HttpFile's Flush() semantics were different than those
documented for files in general.  Flush() used to close the file for
uploading, so that no further writes were allowed, but the documentation
stated that it would only flush data to its destination.  PR #1201
brought HttpFile's Flush() in line with the docs, but gave us no way to
terminate a chunked upload.
This adds a new method to File called CloseForWriting(), which
terminates a chunked upload for HttpFile.  The only other implementation
that does anything is UdpFile, which uses the socket library function
shutdown() to …
=> fix: Fix flush/close semantics for HTTP files, improve testing

.github/workflows/build.yaml, packager/CMakeLists.txt, packager/file/io_cache.h, packager/file/memory_file.cc, packager/file/thread_pool.h, packager/file/threaded_io_file.h, packager/media/base/buffer_writer.h, packager/media/base/fourccs.h, packager/media/base/id3_tag.h, packager/media/base/producer_consumer_queue.h, packager/media/base/proto_json_util.cc, packager/media/chunking/sync_point_queue.h, packager/media/test/test_web_server.h, packager/testing/test_dockers.sh, packager/third_party/abseil-cpp/CMakeLists.txt, packager/third_party/protobuf/CMakeLists.txt, packager/version/version.cc
- Update protobuf to v23.4, to fix the cstdint error on Arch Linux, and make some related changes:
- Silence additional compiler warnings for the new protobuf
- Update absl to 20230125.3, to support the protobuf update, and make some related changes:
- Silence additional compiler warnings for the new protobuf
- Replace GOOGLE_CHECK_OK with ABSL_CHECK_OK
- Replace GUARDED_BY with ABSL_GUARDED_BY
- Update other instances of cstdint missing in our own code
- Always pull the latest docker images, to avoid stale results when your workstation has pulled an older image at the same label
=> fix: Fix compilation on Arch Linux

.gitmodules
Since https://github.com/cesanta/mongoose/issues/2300 was closed, revert to upstream mongoose, specifically the most recent tag "7.11"
=> chore: Revert to upstream mongoose

packager/media/test/CMakeLists.txt, packager/media/test/test_data_util.cc
The `__FILE__` macro does not always get you an absolute path, so our assumptions about it in test_data_util.cc were flawed.
If `foo.c` references `__FILE__`, something like `gcc -c foo.c`, will define `__FILE__` as `"foo.c"`.  If you use `gcc -c /path/to/foo.c`, then `__FILE__` will be `"/path/to/foo.c"`.
The Ninja generator for CMake only generates absolute paths for source files in certain CMake versions.  (Exact range unknown.)  Rather than require newer CMake versions and depend on CMake's Ninja generator maintaining the latest behavior forever, set the macro TEST_DATA_DIR to point to the test data folder.  This is consistent and never depends on unspecified behavior.
This change will allow the use of the Ninja generator with older versions of CMake, as found in most of our Docker …
=> test: Fix data directory computation

packager/testing/dockers/CentOS_Dockerfile, packager/third_party/abseil-cpp/CMakeLists.txt
CentOS 8 is EOL, and the official docker images will not be updated. See https://www.centos.org/centos-linux-eol/
This switches to the latest release (CentOS 9 Stream).  Since CentOS no longer provides official images, this uses a third-party image provider (https://hub.docker.com/u/tgagor)
This change also exposed a warning in absl that needed to be silenced in the default version of GCC in CentOS 9 Stream (GCC 11.4).
=> test: Move CentOS 8 tests to CentOS 9 Stream

.github/workflows/build-matrix.json, .github/workflows/build.yaml, Dockerfile, packager/policies.cmake, packager/testing/dockers/Alpine_Dockerfile, packager/testing/dockers/ArchLinux_Dockerfile, packager/testing/dockers/CentOS_Dockerfile, packager/testing/dockers/Debian_Dockerfile, packager/testing/dockers/Fedora_Dockerfile, packager/testing/dockers/OpenSUSE_Dockerfile, packager/testing/dockers/Ubuntu_Dockerfile, packager/testing/test_dockers.sh
Our workflows and Dockerfiles now use Ninja on Linux & Mac, which enables safe parallel builds.  This significantly speeds up our workflows.
GitHub Actions typical compilation times (build step only):
- Linux 19m => 9m
- macOS 23m => 8m
- Windows 12m => 10m
- Linux arm64 (self-hosted) 72m => 29m
- Docker build 25m => 14m
Overall workflow time: 84m => 33m
Compilation time on my workstation (12 CPUs @3.3GHz): 15m => 3m
This also adds a new environment variable "PACKAGER_LOW_MEMORY_BUILD".  If defined when CMake is first run, this will configure the build to disable parallel linking to reduce memory usage.  This helps us avoid failures on our self-hosted arm64 machines, where 6 CPUs share 4GB of RAM.
NOTE: Parallel builds are **NOT** recommended with Unix Makefiles due to the use of …
=> ci: Enable parallel builds

packager/media/base/container_names_unittest.cc, packager/media/codecs/av1_parser_unittest.cc, packager/media/codecs/h264_parser_unittest.cc, packager/media/formats/mp2t/es_parser_h264_unittest.cc, packager/media/formats/mp2t/mp2t_media_parser_unittest.cc, packager/media/formats/mp4/mp4_media_parser_unittest.cc, packager/media/formats/wvm/wvm_media_parser_unittest.cc, packager/media/test/test_data_util.cc
LOG(FATAL) aborts the executable, which means gtest can't write any reports it might be configured to write when tests are complete.  This will interfere with reporting.
This converts the only use of LOG(FATAL), which was in ReadTestDataFile(), to LOG(ERROR).  This also updates test cases to avoid crashing when ReadTestDataFile() returns an empty buffer.
=> test: Avoid crashing a test executable

.github/workflows/build.yaml, .gitignore, packager/CMakeLists.txt, packager/file/CMakeLists.txt, packager/gtest.cmake, packager/kv_pairs/CMakeLists.txt, packager/media/base/CMakeLists.txt, packager/media/chunking/CMakeLists.txt, packager/media/codecs/CMakeLists.txt, packager/media/crypto/CMakeLists.txt, packager/media/event/CMakeLists.txt, packager/media/formats/webm/CMakeLists.txt, packager/media/trick_play/CMakeLists.txt, packager/status/CMakeLists.txt
All gtest-based tests should now use add_gtest.  Results from these tests will be surfaced more prominently in GitHub Actions.  Before this, it was hard to find test failures in the log.
=> ci: Collect and report test results

.github/workflows/build-docs.yaml, .github/workflows/build.yaml, .github/workflows/docker-hub-release.yaml, .github/workflows/docker-image.yaml, .github/workflows/github-release.yaml, .github/workflows/lint.yaml, .github/workflows/npm-release.yaml, .github/workflows/test-linux-distros.yaml, .github/workflows/update-docs.yaml
Fixes the following warnings from GitHub Actions:
- "The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/"
- "The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/"
=> ci: Fix workflow warnings

packager/app/mpd_generator.cc, packager/app/packager_main.cc, packager/file/file.cc, packager/file/file_test_util.cc, packager/file/file_unittest.cc, packager/file/file_util.cc, packager/file/local_file.cc, packager/media/base/container_names_unittest.cc, packager/media/test/test_data_util.cc
This fixes our use of std::filesystem to interpret all paths names as UTF8.  Before this, UTF8 paths did not work correctly in all cases.
This also adds a new unit test to cover this case.
On Windows, it is critical that a UTF8 locale be set at runtime.  Applications linking with Packager as a library should call setlocale(), and the Packager frontends now do this automatically after converting wide character arguments into narrow strings.
Closes #652
=> fix: Fix local files with UTF8 names

packager/file/http_file_unittest.cc, packager/media/base/http_key_fetcher_unittest.cc, packager/media/test/test_web_server.cc, packager/media/test/test_web_server.h
This will pick a random HTTP port for the test web server, and retry up to 10 times if the chosen port number is in use.
=> test: Use a random HTTP port for web server tests

.github/workflows/build-docs.yaml
Sphinx 7.2.0 breaks Breathe, see sphinx-doc/sphinx#11605 for now pin to 7.1.2 until either of them resolve this issue
=> fix: docs build

packager/hls/base/master_playlist.cc, packager/media/base/video_stream_info.h, packager/media/formats/mp4/box_definitions.cc, packager/media/formats/mp4/box_definitions.h, packager/media/formats/mp4/mp4_media_parser.cc, packager/media/formats/mp4/mp4_muxer.cc
This PR is an extension of the full AV1 codec string feature: [PR 1205](https://github.com/shaka-project/shaka-packager/pull/1205) and relates to [Issue 1007](https://github.com/shaka-project/shaka-packager/issues/1007) and [Issue 1202](https://github.com/shaka-project/shaka-packager/issues/1202). 
As per the AV1 spec, the codec string may contain optional color values. These color values are critical for detecting HDR video streams - see [Issue 1007](https://github.com/shaka-project/shaka-packager/issues/1007). Color information is extracted from the input mp4's `colr` atom and used to generate the full AV1 codec string. This PR preserves the color information by writing the `colr` atom to the muxed mp4. 
**References**:
- [AV1 Codec ISO Media File Format …
=> feat: Write colr atom to muxed mp4

packager/mpd/base/adaptation_set.cc, packager/mpd/base/adaptation_set.h, packager/mpd/base/mpd_utils.h
build in CMake branch is broken at least locally on OS X after #1210 was merged which introduced some new warnings and reintroduced base::nullopt.
=> fix: apply cmake fixes after merge of #1210

link-test/CMakeLists.txt
The link-test targets rebuilt every time you built the project because that is the behavior of commands attached to add_custom_target.  This is fixed by combining add_custom_command and add_custom_target.
Fixing that led to a situation where the link-test targets built on the first build, but didn't properly rebuild when their dependencies changed.  This is fixed by using set_source_file_properties to treat test.cc as dirty when the test-install command runs.
=> build: Fix rebuild of link-test targets

packager/CMakeLists.txt, packager/protobuf.cmake, packager/tools/CMakeLists.txt, packager/tools/pssh/CMakeLists.txt, packager/tools/pssh/README.md, packager/tools/pssh/pssh-box.py
pssh-box.py needs Python protos, which we were not building.  It also needs to have those protos installed properly.
This fixes generation of Python proto interfaces and fixes the install targets to put those protos where they are needed.  This also updates the documentation to match.
=> build: Fix pssh-box.py targets, installation, and docs

packager/hls/CMakeLists.txt, packager/utils/CMakeLists.txt
This caused issues with some shared library link tests when I tried to split the library target into shared and static targets.
=> fix: Fix internal libraries built as dynamic by default

.github/workflows/build.yaml, .gitmodules, Dockerfile, docs/source/build_instructions.md, packager/testing/dockers/Alpine_Dockerfile, packager/testing/dockers/ArchLinux_Dockerfile, packager/testing/dockers/CentOS_Dockerfile, packager/testing/dockers/Debian_Dockerfile, packager/testing/dockers/Fedora_Dockerfile, packager/testing/dockers/OpenSUSE_Dockerfile, packager/testing/dockers/Ubuntu_Dockerfile, packager/third_party/CMakeLists.txt, packager/third_party/c-ares/CMakeLists.txt, packager/third_party/curl/CMakeLists.txt
c-ares (used on Linux only) was an exception to the rule of only linking against internally-built libraries.  This fixes that, to support a truly static build of packager.
=> feat: Build c-ares locally

.gitmodules
The upstream repo at gnome.org sometimes fails in CI
=> fix: Use stable GitHub mirror for libxml2 source

packager/third_party/abseil-cpp/CMakeLists.txt
=> fix: Fix clang build

.github/workflows/build.yaml, CMakeLists.txt, docs/source/build_instructions.md, link-test/CMakeLists.txt, packager/CMakeLists.txt, packager/file/CMakeLists.txt, packager/status/CMakeLists.txt
Use the standard BUILD_SHARED_LIBS variable instead of the custom LIBPACKAGER_SHARED variable
=> build: Use the standard BUILD_SHARED_LIBS variable

packager/CMakeLists.txt
This splits the target so that we always build static libraries, but optionally also build shared libraries.  This also tweaks the installation so that the static library is never installed, because it is not usable without the other internal static library deps.  The headers and pkgconfig will only be installed if we have a shared library to use them with.
=> build: Separate shared and static library targets

AUTHORS, CONTRIBUTORS, packager/hls/base/tag.h, packager/hls/public/hls_params.h, packager/media/base/buffer_writer.h, packager/media/base/fourccs.h, packager/media/base/id3_tag.h, packager/media/base/id3_tag_unittest.cc, packager/packager.h
CC version 13 needs `<cstdint>` to be explicitly included to
provide fixed bits integer types.
Some files using it inludes `<stdint.h>`, some are missing direct or undirect inclusion. This PR adds `<cstdint>` inclusion to the
minimal set of files, allowing compilation on GCC 13.
Closes #1305
=> fix: Add missing <cstdint> includes

packager/utils/string_trim_split.cc
The accidental tolower in `SplitAndTrimSkipEmpty` was causing stream descriptors to not preserve case for certain things like accessibilities.
=> fix: preserve case for stream descriptors

packager/media/formats/mp4/mp4_muxer.cc, packager/packager.cc
The fix in #1289 was not complete and left the fake clock as null which didn't have any effect. This was revealed by integration tests showing mismatches in the timestamps in MP4.
=> test: fix fake clock for muxer for integration tests

include/packager/packager.h, packager/app/muxer_flags.cc, packager/app/muxer_flags.h, packager/app/packager_main.cc, packager/media/formats/webvtt/text_padder.cc, packager/packager.cc
A positive value, in milliseconds. It is the threshold used to determine if we should assume that the text stream actually starts at time zero. If the first sample comes before default_text_zero_bias_ms, then the start will be padded as the stream is assumed to start at zero. If the first sample comes after default_text_zero_bias_ms then the start of the stream will not be padded as we cannot assume the start time of the stream.
=> feat: default text zero bias

.github/workflows/build.yaml, CMakeLists.txt, docs/source/build_instructions.md, packager/CMakeLists.txt, packager/testing/dockers/Debian_Dockerfile, packager/testing/dockers/Fedora_Dockerfile, packager/testing/dockers/OpenSUSE_Dockerfile, packager/testing/dockers/Ubuntu_Dockerfile
According to a comment in
packager/third_party/abseil-cpp/source/absl/log/CMakeLists.txt, many linkers will strip the contents of absl::log_flags because its symbols symbols are only used in a global constructor, and that for now, clients should link using
$<LINK_LIBRARY:WHOLE_ARCHIVE,absl::log_flags>.
Closes #1325
=> build: Fix absl log flags being stripped

packager/media/codecs/h265_byte_to_unit_stream_converter.cc
ISO/IEC 14496-15 says about the `HEVCDecoderConfigurationRecord`:
> **array_completeness** when equal to 1 indicates that all NAL units of the given type are in the following
array and none are in the stream; when equal to 0 indicates that additional NAL units of the indicated type may be in the stream; the default and permitted values are constrained by the sample entry name;
This PR sets `array_completeness` to 0 if parameter NAL units may appear in the stream when they are not stripped by `--strip_parameter_set_nalus`.
This should increase player-compatibiltity for streams with mid-stream SAR changes.
=> fix: set array_completeness in HEVCDecoderConfigurationRecord correctly

packager/hls/base/media_playlist.cc
Minor fix. The parameters were swapped.
=> fix: misleading log output when HLS target duration updates (fixes #969)

packager/file/http_file.cc
In some cases it can happen that the http server responds with a non-successful status code without reading the response body. In this case curl may decide not to read from the cache since there is really no point in sending data to the server. In case some other thread of shaka has already called HttpFile::Flush it may end up deadlocked there waiting for the cache to either close or become empty. Thus, we close the cache when leaving the main thread as no data will be read by curl after it has finished anyways.
Closes #1347
=> fix: http_file: Close upload cache on task exit

packager/app/mpd_generator.cc, packager/app/packager_main.cc
This tweaks the default config for stderrthreshold from absl/log so that we always get logs to stderr by default, as we did in v2.  The --quiet and --v flags that existed in v2 can still be used to modify the log level, as well as the new --minloglevel from absl/log.
Issue #1325
=> fix: Always log to stderr by default

packager/app/packager_main.cc
Without this, the command prompt will not appear on its own line after running `packager` with no arguments.
=> fix: Fix missing newline at the end of usage

packager/third_party/CMakeLists.txt
We already disabled warnings-as-errors in third-party code, but this goes futher to completely disable third-party warnings.  They are mostly noise, and distracting.  If they aren't errors, we shouldn't have our build logs flooded with them.
=> build: Disable warnings in third-party code

.github/workflows/release-please.yaml
The build invocation from the release workflow needs settings to trigger self-hosted builds, including Linux arm64.
=> ci: Add missing arm64 (self-hosted) builds on release

.github/workflows/build-matrix.json, .github/workflows/build.yaml
Support for this came out in January, 2024.  Explicit macos versions seem to be necessary for now, until GitHub offers "latest" labels targeting specific architectures.
=> fix(CI): Add Mac-arm64 to build matrix

.github/workflows/build.yaml, .github/workflows/publish-docker.yaml, .github/workflows/release-please.yaml, packager/version/generate_version_string.py
The release workflows did not run checkout with `fetch-tags: true`, so the builds were unable to compute the correct release version number. I audited all instances of `actions/checkout` to add `fetch-tags` where needed and clean up unneeded options.
I also had to fix options to `docker/build-push-action`, which by default ignores `actions/checkout` and tries to pull from git itself.  This led to the Docker build running in a context without the new tag.
Finally, to make verification easier and provide version info in the build logs, this adds debugging info to the version-generation script via stderr.
Closes #1366
=> fix: Fix tags in official Docker images and binaries

.github/workflows/publish-npm.yaml, npm/.npmignore, npm/prepublish.js
The default .npmignore would disallow bin/, which contains binaries for our NPM release.  Every release before v3.0.3 was missing .npmignore, and therefore had no binaries.  These were unusable in NPM, and have been marked as deprecated because of it.
Closes #1369
=> fix: Fix NPM binary publication

packager/mpd/base/mpd_builder.cc
The check for `!mpd_dir.empty()` is not needed because MakePathRelative handles the case where the parent path is empty. As a result of this check the base url, segment url, or segment template URLs were all missing in cases where the mpd output was in the current working directory.
Fixes #1378
=> fix: BaseURL missing when MPD base path is empty

packager/mpd/base/adaptation_set.cc, packager/mpd/base/adaptation_set.h, packager/mpd/base/period.cc, packager/mpd/base/period.h
This change is related to https://github.com/google/shaka-packager/issues/733.
=> refactor: merge Period::ProtectedAdaptationSetMap  into AdaptationSet

docs/source/options/widevine_encryption_options.rst
The option was never covered to the widevine docs when it was added, requiring someone to read the source code or the --help to discover this option.
Fixes #983
=> docs: document --enable_entitlement_license option for Widevine

packager/mpd/CMakeLists.txt, packager/mpd/base/mpd_builder.cc, packager/mpd/base/xml/xml_node.cc, packager/mpd/base/xml/xml_node.h
Currently `media_info.media_file_url()` is not escaped when placed into MPD for things like BaseURL. This for example breaks when trying to us a file name that contains special characters like &. Since these are supposed to be URLs let's URL encode them.
Fixes #1107
=> fix: escape media URLs in MPD

packager/media/codecs/vp9_parser.cc
If color_space is VPX_COLOR_SPACE_SRGB, the specs says that color_range should be 1 i.e. yuv_full_range = true. However, yuv_full_range is default initialized as false and isn't set in the branch for color_space is VPX_COLOR_SPACE_SRGB.
Fixes #990
=> fix: set yuv full range flag to 1 for VP9 with sRGB

AUTHORS, CONTRIBUTORS, packager/mpd/base/period.cc
As per issue #1418, several Dash roles are missing from the RoleFromString function, making them unusable in practice. This update should enable them for use.
=> fix: Add Missing Dash Roles to RoleFromString function (#1418)

packager/third_party/protobuf/CMakeLists.txt, packager/third_party/protobuf/protobuf_py.cmake, packager/tools/pssh/CMakeLists.txt, packager/tools/pssh/pssh-box.py
This embeds the full python protobuf library into the output in pssh-box-protos, which is used by installation targets and Docker images.  Without this, the installed pssh-box.py tool would depend on a separate installation of the python protobuf library.
Closes #1436
=> fix: Embed full python protobuf library

packager/file/http_file.cc, packager/third_party/curl/CMakeLists.txt
Upgrading curl fixes errors like "Failed sending data to the peer" flooding the log.  This is described upstream in https://github.com/curl/curl/issues/10591 and fixed in curl 8.2.0.  Here we upgrade to curl 8.9.1 (latest as of today).
This required updating the way we attach c-ares to libcurl and updating CURLOPT_PUT (deprecated) to CURLOPT_UPLOAD (compatible equivalent AFAICT).
=> fix(http): Fix "Failed sending data to the peer" errors

docs/source/tutorials/http_upload.rst, packager/file/file.cc, packager/file/http_file.cc, packager/file/http_file.h, packager/file/http_file_unittest.cc
When we try to remove an old segment from a live stream we uploaded via HTTP, we need to send DELETE requests.
=> feat(http): Add DELETE method support

docs/source/options/hls_options.rst, include/packager/hls_params.h, packager/app/hls_flags.cc, packager/app/hls_flags.h, packager/app/packager_main.cc, packager/hls/base/master_playlist.cc, packager/hls/base/master_playlist.h, packager/hls/base/master_playlist_unittest.cc, packager/hls/base/media_playlist.cc, packager/hls/base/media_playlist.h, packager/hls/base/simple_hls_notifier.cc
* adding EXT-X-SESSION-KEY to master_playlist.cc
* adding 'create_session_keys' command-line option
* adding unit test
=> feat: EXT-X-SESSION-KEY support (#36)

packager/media/codecs/iamf_audio_util.cc, packager/media/codecs/iamf_audio_util_unittest.cc
These errors were specifically coming up in Windows builds and in Linux release builds.  This initializes those variables.
This also fixes errors in IAMF tests like "offset 2 out of bounds", which some compilers raise when you try to statically initialize a vector, then add to it later.
=> chore: Fix "potentially uninitialized variable" errors in IAMF

.github/workflows/pr.yaml, .github/workflows/release-please.yaml
This was found by auditing workflows based on research published here:
https://github.com/joeyparrish/workflow-cheat-sheet
The research was prompted by a workflow bug in Shaka Streamer
=> ci: Fix workflow events

packager/file/http_file.cc
When uploading a live stream, if a single segment upload fails, we shouldn't give up.
This adds an option to ignore HTTP output failures so that a single failed upload does not result in a hung stream.  See https://github.com/shaka-project/shaka-streamer/issues/195 for details.
=> feat: Add option to ignore HTTP output failures

.github/workflows/build.yaml, packager/testing/dockers/Ubuntu_Dockerfile
This should fix the retrieval of the GPG key and allow an updated cmake to be installed.
=> ci: Ignore cert error for apt.kitware.com

.github/workflows/release-please.yaml
Now that default permissions are read-only, we must enable specific permissions for certain workflow jobs.
=> ci: Update workflow permissions

.github/workflows/build-docker.yaml, .github/workflows/build-docs.yaml, .github/workflows/build.yaml, .github/workflows/lint.yaml, .github/workflows/publish-docker.yaml, .github/workflows/publish-npm.yaml, .github/workflows/release-please.yaml, .github/workflows/test-linux-distros.yaml
See actions/checkout#485 and https://johnstawinski.com/2024/01/11/playing-with-fire-how-we-executed-a-critical-supply-chain-attack-on-pytorch/
In short, it is a terrible idea to persist even our default credentials after checkout. There's no call for that, so we will now set `persist-credentials: false` on all checkout actions.
=> ci: Do not persist credentials after checkout

.github/workflows/lint.yaml, packager/app/test/packager_test.py, packager/tools/git/pylintrc, packager/tools/pssh/pssh-box.py
Also fixes issues raised by the newer, stricter pylint
=> ci: Upgrade pylint to support Python 3.12

.github/workflows/release-please.yaml
google-github-actions/release-please-action has been deprecated and replaced with googleapis/release-please-action.
=> fix(ci): Fix incomplete 3.4.1 release

build-matrix.json
These are no longer required since GitHub launched their own Linux/arm64 runners.
See https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
=> ci: Stop using self-hosted Linux/arm64 runners

.github/workflows/settings.yaml
Since the introduction of `vars` to GitHub Actions, I started using that instead of the "environments" trick I used in Packager.  However, it has become clear now that the `vars` strategy has major drawbacks, such as requiring the use of `pull_request_target`, which should only be used for actions that do not execute PR-author-controlled code.
This updates the comments to clarify why this is used.  This reusable settings workflow will also be deployed now in other repos to standardize on this "environments" mechanism, which is safer than `vars`.
=> ci: Update comments for the settings workflow

.github/workflows/build-docker.yaml, .github/workflows/publish-docker.yaml, .github/workflows/test-linux-distros.yaml, packager/testing/dockers/ArchLinux_Dockerfile, packager/testing/dockers/CentOS_Dockerfile
This adds support for Docker-based testing on arm64 images and runners.
This also adds a multiarch build process so that future releases cover both x64 and arm64.
This is tagged as "feat" so that this gets called out in the changelog for the next release.
=> feat(ci): Official multiarch docker images for x64 + arm64
