AUTHORS
CONTRIBUTORS
packager/media/file/udp_file_posix.cc

Check return value of setsockopt function call (SO_REUSEADDR)

Do not require exclusive bind of udp sockets

---

packager/media/demuxer/demuxer.cc

Change-Id: I88bfdee9020a6abb96d6d38397263c08773501df

Fix Windows 64 break

---

packager/media/formats/mpeg/adts_constants.cc

Standard specifies 3 channels (from,left,rigth) for channel configuration value equal to 3

[fix] kAdtsNumChannelsTable

---

AUTHORS
CONTRIBUTORS
packager/media/codecs/h265_byte_to_unit_stream_converter.cc
packager/media/codecs/h265_byte_to_unit_stream_converter_unittest.cc

Fix order of VPS, SPS, PPS in hvcC box of HEVC/MP4

---

packager/media/demuxer/demuxer.h
packager/media/formats/mp4/segmenter.h

Remove non-exist class MediaStream.

---

docs/source/options/hls_stream_descriptors.rst
packager/app/packager_main.cc

Make it clear that shaka packager will create the playlist file. (See #305.)

Update playlist_name docs

---

docs/source/options/udp_file_options.rst
packager/file/udp_file.cc
packager/file/udp_options.cc
packager/file/udp_options.h
packager/file/udp_options_unittest.cc

Source Specific Multicast support

---

packager/hls/base/simple_hls_notifier.cc
packager/packager.cc

This PR will unify "no else return".
- Unify code format
- Low nest level

no else return

---

packager/media/codecs/aac_audio_specific_config.cc
packager/media/codecs/aac_audio_specific_config.h
packager/media/formats/mp2t/pes_packet_generator.cc
packager/media/formats/mp2t/pes_packet_generator_unittest.cc
packager/media/formats/packed_audio/packed_audio_segmenter.cc
packager/media/formats/packed_audio/packed_audio_segmenter_unittest.cc

This PR will use copied ADTS header.
This PR is needed to reduce unnecessary copying ADTS header.

Reduce copying ADTS header

---

packager/app/mpd_flags.cc

Remove the 'Exclusive' statements once

---

packager/media/trick_play/trick_play_handler.cc
packager/mpd/base/period.cc
packager/mpd/base/period.h
packager/mpd/base/period_unittest.cc

This PR is related to https://github.com/google/shaka-packager/issues/732

[DASH] Support TrickPlay using separate trick play specific streams

---

packager/app/test/packager_test.py
packager/app/test/testdata/audio-video-with-accessibilities-and-roles/bear-english-text.vtt
packager/app/test/testdata/audio-video-with-accessibilities-and-roles/output.mpd
packager/packager.cc

Consider DASH stream descriptor field "roles" for WebVTT text streams.

---

packager/media/formats/webm/segmenter.cc

Prevent seg fault when finalizing empty segment

---

AUTHORS
CONTRIBUTORS
packager/media/codecs/h265_parser.cc

Should use value from slice header as the default might get overwritten.

Fixed inaccurate parsing of ref pic list modification (#717)

---

AUTHORS
CONTRIBUTORS
README.md
packager/app/muxer_factory.cc
packager/media/base/audio_stream_info.cc
packager/media/base/container_names.cc
packager/media/base/fourccs.h
packager/media/base/stream_info.h
packager/media/formats/mp2t/es_parser_audio.cc
packager/media/formats/mp2t/mp2t.gyp
packager/media/formats/mp2t/mp2t_media_parser.cc
packager/media/formats/mp2t/mpeg1_header.cc
packager/media/formats/mp2t/mpeg1_header.h
packager/media/formats/mp2t/mpeg1_header_unittest.cc
packager/media/formats/mp2t/pes_packet_generator.cc
packager/media/formats/mp2t/program_map_table_writer.cc
packager/packager.cc

- Can parse mpeg audio elementary streams in mpeg2ts
- Can output files in .mp3 format

Support for MPEG Audio in mpeg2ts I/O and packed-audio output

---

packager/media/formats/mp2t/ts_segmenter.cc
packager/media/formats/mp2t/ts_segmenter.h
packager/media/formats/mp2t/ts_segmenter_unittest.cc
packager/media/formats/mp2t/ts_writer.cc
packager/media/formats/mp2t/ts_writer.h
packager/media/formats/mp2t/ts_writer_unittest.cc

PR 1 for Omit Segment Timeline Issue.

Write to buffer before writing to file for TS segments generation.

---

packager/media/formats/webm/segmenter.cc
packager/media/formats/webm/webm_muxer.cc

prevent seg fault if webm fragment is not initialized or last frame is EOS

---

packager/media/formats/webvtt/webvtt_parser.cc
packager/media/formats/webvtt/webvtt_parser_unittest.cc

bugfix- WEBVTT Region parse 100 precent

---

packager/file/file.cc

For a read mode, make a GET request.  Otherwise, make a PUT request.

feat: Respect the file mode for HttpFiles

---

.github/workflows/build.yaml

ci: Fix build workflow in arm64 self-hosted

---

AUTHORS

Add my name to the AUTHORS list.

docs: Update AUTHORS

---

packager/file/udp_file.cc

fix: Fix UdpFile build on FreeBSD

---

.gitmodules
packager/third_party/zlib/CMakeLists.txt

The issues we had with zlib and CMake have been resolved upstream.

chore: Unfork zlib

---

packager/CMakeLists.txt

build: Only ever build static or shared libraries, but never both

---

packager/media/formats/mp4/box_definitions.cc

fix: AudioSampleEntry size caluations due to bad merge

---

npm/index.js

fix: Fix NPM binary selection on ARM Macs

---

.github/workflows/build-docs.yaml

docs: Fix missing graphviz outputs in generated docs
